[package]
edition = "2024"
name = "embassy-rp2350-examples"
version = "0.1.0"
license = "MIT OR Apache-2.0"

publish = false

[dependencies]
# Embassy crates pulled directly from GitHub instead of local ../../ paths
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy.git", rev = "abc8e450f936567ad42cb34b5d2a7941b206aa5d", features = ["defmt"] } # version = "0.5.0"
embassy-sync          = { git = "https://github.com/embassy-rs/embassy.git", rev = "abc8e450f936567ad42cb34b5d2a7941b206aa5d", features = ["defmt"] } # version = "0.7.2"
embassy-executor      = { git = "https://github.com/embassy-rs/embassy.git", rev = "286d887529c66d8d1b4c7b56849e7a95386d79db", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt"] } # version = "0.9.0"
embassy-time          = { git = "https://github.com/embassy-rs/embassy.git", rev = "a6a38cdd22cb2f47f3cc869f447d7cdb80e27ec6", features = ["defmt", "defmt-timestamp-uptime"] } # version = "0.5.0"
embassy-rp            = { git = "https://github.com/embassy-rs/embassy.git", branch = "main", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl", "rp235xa", "binary-info"] }
embassy-usb           = { git = "https://github.com/embassy-rs/embassy.git", branch = "main", features = ["defmt"] }
embassy-net           = { git = "https://github.com/embassy-rs/embassy.git", branch = "main", features = ["defmt", "icmp", "tcp", "udp", "raw", "dhcpv4", "medium-ethernet", "dns"] }
embassy-net-wiznet    = { git = "https://github.com/embassy-rs/embassy.git", branch = "main", features = ["defmt"] }
embassy-futures       = { git = "https://github.com/embassy-rs/embassy.git", branch = "main" }
embassy-usb-logger    = { git = "https://github.com/embassy-rs/embassy.git", branch = "main" }

# CYW43 Wi-Fi + PIO driver
cyw43     = { git = "https://github.com/embassy-rs/embassy.git", branch = "main", features = ["defmt", "firmware-logs"] }
cyw43-pio = { git = "https://github.com/embassy-rs/embassy.git", branch = "main", package = "cyw43-pio", features = ["defmt"] }

# Other dependencies
defmt = "1.0.1"
defmt-rtt = "1.0.0"
fixed = "1.23.1"
fixed-macro = "1.2"

serde = { version = "1.0.203", default-features = false, features = ["derive"] }
serde-json-core = "0.5.1"

# for assign resources example
assign-resources = { git = "https://github.com/adamgreig/assign-resources", rev = "bd22cb7a92031fb16f74a5da42469d466c33383e" }

# for TB6612FNG example
tb6612fng = "1.0.0"

cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = "0.7.0"
critical-section = "1.1"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
display-interface-spi = "0.5.0"
embedded-graphics = "0.8.1"
mipidsi = "0.8.0"
display-interface = "0.5.0"
byte-slice-cast = { version = "1.2.0", default-features = false }
smart-leds = "0.3.0"
heapless = "0.8"
usbd-hid = "0.8.1"

embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
embedded-hal-async = "1.0"
embedded-hal-bus = { version = "0.1", features = ["async"] }
embedded-io-async = { version = "0.6.1", features = ["defmt-03"] }
embedded-storage = { version = "0.3" }
static_cell = "2.1.0"
portable-atomic = { version = "1.5", features = ["critical-section"] }
log = "0.4"
embedded-sdmmc = "0.7.0"

[profile.release]
# Enable generation of debug symbols even on release builds
debug = true

[package.metadata.embassy]
build = [
  { target = "thumbv8m.main-none-eabihf", artifact-dir = "out/examples/rp235x" }
]
