[package]
name = "pico2w-cyw43-blink"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"

rp235x-hal = { version = "0.3", features = ["rt", "cyw43"] }

panic-halt = "0.2"

[profile.release]
opt-level = "z"
lto = true
