[package]
name = "pico2w-cyw43-blink"
version = "0.1.0"
edition = "2021"

[dependencies]
rp235x-hal = { version = "0.3", features = ["cyw43"] }
cyw43-pio = "0.2"
cortex-m = "0.8"
cortex-m-rt = "0.7"
panic-halt = "0.2"
embedded-hal = "1.0.0-alpha.7"
nb = "1.0"

[profile.release]
lto = true
codegen-units = 1
