[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP235x"
#runner = "elf2uf2-rs -d"
#runner = "picotool load -u -v -x -t elf"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"

[target.thumbv8m.main-none-eabihf]
rustflags = ["-C", "link-arg=-Tlink_rp235x.x",]
